version: "3.8"

services:
  bot:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: bot
    hostname: bot
    env_file:
      - ./.env
    volumes:
      - .:/work
    working_dir: /work
    command: sh entrypoint.sh
  